### ISSUE TITLE
Tree building is too slow

### ISSUE THREAD

**Issue by hankyusa** [hankyusa/UNMFall18_ML_Project1DecisionTrees#1]
I had to reduce the training data down to 1% of the original instances in order to test in any reasonable amount of time. I shudder to think of how long it would take to do all 2000 training instances. 

I don't know how to test performance of individual bits of code.

Sibling nodes could be constructed in parallel.

**Comment by trevorlapay** [comment]
I see it too. I'll take a look this weekend. Thanks for building out so much of this already!

**Comment by trevorlapay** [comment]
The algorithm looks correct to me per her notes, but maybe you can explain some behavior I'm seeing. It looks like it correctly picks a feature (37 or something) for the root node. However, when it recurses on the first feature type (i.e. 'A') for that node, all of the gains are zero, so it picks the first feature (0) out of the feature list and keeps recursing down that side of the tree. Subsequent recursions also yield zero gains across all features, but I didn't follow the algorithm too far after that. Is this some wacky feature of the dataset? It seems like if all gains are zero, then there's no good reason to keep growing out the tree for that particular feature type. I didn't dig too deeply, so I may be missing something obvious.

**Comment by hankyusa** [comment]
I think I fixed the performance issue. A node would generate children even if it had entropy of 0. This lead to trees with 60^8 nodes at the base. 

Now I'm getting  a single instance of the training data that the tree doesn't classify correctly. I don't think that should be possible with a correct implementation of the algorithm. The submission file is getting graded at 87.394% accuracy which is not bad in my book.

**Comment by trevorlapay** [comment]
The single attribute classifying incorrectly possible and expected when there are duplicates in the training list. That's an "error" in the training data. We should strip dupes from the list unless we have a way of knowing which one is valid, although in this case it shouldn't affect our tree. Otherwise, this is working exactly as expected
