### ISSUE TITLE
Chi square not helping...

### ISSUE THREAD

**Issue by trevorlapay** [hankyusa/UNMFall18_ML_Project1DecisionTrees#3]
No matter how I tweak the chi square inputs, the best I can do on the kaggle prediction submit is 80% correct. It could be that the test data is fit very snugly with the training data, or it could be something is off with my implementation.

**Comment by trevorlapay** [comment]
I spoke with the TA regarding my implementation:


From TA:

> "I apologize for taking a bit to respond. I have gone through your chi squared implementation and the only issue that I see is where you calculate the degrees of freedom:
    if getChiSquareForSplit(df, featId) > getCritValue(q, (len(featVals) - 1) * (len(allFeatIDs) - 1)):

> The calculation (from the lecture on Thursday) should be (#classes-1) *( #feature Values -1).  It looks like your degrees of freedom is way to high since you are using the number of features rather than the number of values that the features can take."

 
However, in the lecture notes, Trice labeled them "features" rather than "featureValues," but I will take the TA's word for it and make the change.

**Comment by trevorlapay** [comment]
Ok, so this gives a much better result (~97% accurate when tested against the training set, ~87% when tested on submission), but it doesn't beat the best score (88%) which uses Gini Index and avoids using chi square pruning.

**Comment by hankyusa** [comment]
Regarding |features| vs |feature values|, I have |feature values| in my notes. I believe your right about what she wrote on the board, but I think she verbally clarified so I made it less ambiguous.
