### ISSUE TITLE
strange calculations in `getChiSquareForSplit` function

### ISSUE THREAD

**Issue by hankyusa** [hankyusa/UNMFall18_ML_Project1DecisionTrees#4]
@trevorlapay

I made [a video explaining the issue](https://youtu.be/RnKLm89zwyU). The short version: In the `getChiSquareForSplit` function `numParentObserved` and `numClassTotal` are always equal. I don't believe that is what you intended.

Here is the code shown in the video.

```python
# Calculate the chi square for a given dataframe
def getChiSquareForSplit(df, featId):
    chiVal = 0
    # Get count of ALL of parent's instances (regardless of class).
    numParentTotal = len(df)
    for classType in allClasses:
        # Get the set of parent's instances matching classType.
        df_c = getInstances(df, None, None, classType)
        # Get count of parent's instances matching classType.
        numParentObserved = len(df_c)
        if (numParentObserved) > 0:
            # numClassTotal = total count of number of instances in candidate child node
            numClassTotal = len(getInstances(df_c, None, None, classType))
            if numParentObserved != numClassTotal: print("numParentObserved != numClassTotal")
            # Get the expected value for chi square.
            expected = numParentObserved * numClassTotal / numParentTotal
            for featureVal in featVals:
                actual = len(getInstances(df_c, featId, featureVal, classType))
                chiNumerator = math.pow(actual-expected, 2)
                chiVal += chiNumerator/expected
    return chiVal
```

Here is the code prior to my commenting and refactoring.

```python
# helper for getting EV for chi square.
# numParentActual = actual number of a specific class instance in parent node.
# numClassTotal = total count of number of instances in candidate child node
# numParentTotal = total count of all instances in a parent node
def getExpectedValue(numParentObserved, numClassTotal, numParentTotal):
    return numParentObserved * (numClassTotal / numParentTotal)

# Calculate the chi square for a given dataframe
def getChiSquareForSplit(df, featId):
    chiVal = 0
    for classType in allClasses:
        df_c = getInstances(df, None, None, classType)
        numParentObserved = len(df_c)
        if (numParentObserved) > 0:
            numParentTotal = len(df)
            numClassTotal = len(getInstances(df_c, None, None, classType))
            for featureVal in featVals:
                expected = getExpectedValue(numParentObserved, numClassTotal, numParentTotal)
                actual = len(getInstances(df_c, featId, featureVal, classType))
                chiNumerator = math.pow(actual-expected, 2)
                chiVal += chiNumerator/expected
    return chiVal
```

**Comment by trevorlapay** [comment]
Thanks, I'll take a look again.

**Comment by trevorlapay** [comment]
Thanks for the video... I see what I did wrong. I should have filtered by
everything BUT class in the numClassTotal calculation to get the total
contents of a given child node.

That said, I'm still not getting great results when I use the
splitDecision. I think I'm going to visit Trilce in office hours to see if
I missed something big, because as I understand it, this should prune nodes
that don't add value.

I'll check in my changes with comments tonight.

**Comment by hankyusa** [comment]
I think I might know what's wrong with the chi-square statistic. I think that we're supposed to consider spawning each child node independent of the others. That is each candidate child node gets its own `chiVal` which is compared to the threshold. Chi-square could block two children from being made but allow the rest. I haven't tested this idea yet. I'm going to write a `shouldSpawn` function as to not mess with the ones you've already written.

**Comment by trevorlapay** [comment]
I've thought about this and was planning on asking Trilce the same on Tues.
Thanks!

**Comment by hankyusa** [comment]
After testing, I think my previous comment was wrong. If you want to try it out yourself, I pushed the method I wrote for the `DecisionNode` class.
